### ISSUE TITLE
Question: Is it possible to configure all test executions from a central point

### ISSUE THREAD

**Issue by fkromer** [avocado-framework-tests/avocado-misc-tests#729]
Is it possible to define the configuration of all or several tests in one central place instead of in the test specific configuration files? E.g. test [/io/pci/pci_hotplug.py](https://github.com/avocado-framework-tests/avocado-misc-tests/blob/master/io/pci/pci_hotplug.py) is configured in the configuration file [/io/pci/pci_hotplug.py.data](https://github.com/avocado-framework-tests/avocado-misc-tests/tree/master/io/pci/pci_hotplug.py.data).

**Comment by narasimhan-v** [comment]
@fkromer Can you explain in detail please ?

**Comment by fkromer** [comment]
@narasimhan-v Right now a user of the repository needs to fork it to being able to configure the tests specific to the users system in a lot of different configuration files. If one would be able to configure the overall set of test suites/tests the user could hold this information in one central "place" potentially separate from the repository. However this is no proposal but a question. If this is not possible to fork the repository is totally fine.

**Comment by narasimhan-v** [comment]
@fkromer Since the config (yaml) files are dependent on the test scripts, I guess having a separate repository for config will add a lot of maintenance overhead, and deviations. But having one single yaml file for more test / test suites is possible, and can be maintained as your fork downstream, as per the requirements.

**Comment by narasimhan-v** [comment]
> It is about to override the default config in the separate yaml files with user specific config values from one single yaml file.

You can do that.

>Where can I find info about how to configure several tests/test suites in one single yaml file?

@fkromer That is just to collate all yaml parameters of tests into one single yaml, though it is not as easy. You would need to take care of conflicting parameters

**Comment by fkromer** [comment]
@narasimhan-v I just keep our fork of the repo with custom configuration. Makes maintenance a lot easier.

**Comment by apahim** [comment]
You can use the YAML test loader:
http://avocado-framework.readthedocs.io/en/latest/optional_plugins/yaml_loader.html

Long story short, there's a specific YAML key (`test_reference`) that can be understood by the Avocado loader to be used as the test reference. The rest of the file is just a regular Avocado YAML parameters file, but the variants will be created per test_reference, meaning each `test_reference` will have a different set of variants and parameters. Example:

```yaml
!mux
testcase_01:
    test_reference: passtest.py
    !include : passtest.py.data/passtest.yaml
testcase_02:
    test_reference: sleeptest.py
    variants: !mux
        slow:
            timeout: 1
        fast:
            timeout: 1
testcase_03:
    test_reference: failtest.py
    variants: !mux
        foo:
            p1: 1
        bar:
            p1: 10
``` 
And then run with:
```
$ avocado run testcases.yaml
```
